apiVersion: v1
kind: Service
metadata:
  name: cnf-q-service
spec:
  selector:
    app: cnf-q-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
  type: NodePort
